import { StyleSheet, Platform, StatusBar } from "react-native";

export default StyleSheet.create({
  AndroidSafeArea: {
    flex: 1,
    paddingTop: Platform.OS === "android" ? StatusBar.currentHeight + 5 : 5,
  },
  pageContainer: {
    flex: 1,
    color: "#fff",
  },
  scrollView: {
    flex: 1,
  },
  pageGradient: {
    flex: 1,
  },
  pageTitle: {
    textAlign: "center",
    fontWeight: "500",
    fontSize: 30,
    letterSpacing: -0.6,
    marginBottom: 8,
    color: "#f4f4f4",
  },
  textInput: {
    backgroundColor: "#3b3b3b",
    color: "#fff",
    fontSize: 18,
    padding: 8,
    borderRadius: 3,
    width: 150,
  },
  configContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  configLabel: {
    fontSize: 20,
    marginRight: 10,
    color: "#f4f4f4",
  },
  configSection: {
    flexDirection: "row",
    margin: 13,
    alignItems: "center",
  },
  submitConnect: {
    backgroundColor: "#007aff",
    borderRadius: 3,
    padding: 10,
    margin: 15,
  },
  errorMessage: {
    color: "#f4f4f4",
  },
  buttonText: {
    color: "#f4f4f4",
  },
  containerTitleText: {
    color: "#979797",
    fontWeight: "700",
    textTransform: "uppercase",
    fontSize: 15,
  },
  containerTitle: {
    flexDirection: "row",
    justifyContent: "space-between",
    backgroundColor: "#1e1e1e",
    borderBottomColor: "#363636",
    borderBottomWidth: 1,
    paddingTop: 9,
    // paddingRight: 13,
    paddingBottom: 7,
    paddingLeft: 11,
    borderTopLeftRadius: 7,
    borderTopRightRadius: 7,
  },
  module: {
    borderWidth: 1,
    borderColor: "#717171",
    shadowColor: "#141414",
    shadowOffset: {
      width: 0,
      height: 7,
    },
    shadowOpacity: 0.43,
    shadowRadius: 9.51,
    elevation: 15,
    borderRadius: 7,
    backgroundColor: "#2f2f2f",
    marginHorizontal: 10,
    marginVertical: 5,
    // width: "95%",
  },
  timerBox: {
    flexDirection: "row",
    alignItems: "center",
    paddingTop: 5,
    paddingRight: 20,
    paddingBottom: 5,
    paddingLeft: 10,
    borderBottomColor: "#363636",
    borderBottomWidth: 1,
  },
  finalTimerBox: {
    width: "200%",
    flexDirection: "row",
    alignItems: "center",
    paddingTop: 5,
    paddingRight: 20,
    paddingBottom: 5,
    paddingLeft: 10,
    // backgroundColor: "#ffffff",
  },
  timerTime: {
    marginLeft: 14,
  },
  containerSlides: {
    flexDirection: "row",
    justifyContent: "space-evenly",
    flexWrap: "wrap",
  },
  slideNumber: {
    fontSize: 12,
    backgroundColor: "#1e1e1e",
    paddingVertical: 1,
    paddingHorizontal: 6,
    color: "#f4f4f4",
  },
  slideBox: {
    borderWidth: 1,
    borderColor: "#363636",
    margin: 3,
  },
  currentSlide: {
    borderWidth: 2,
    borderColor: "#ff7414",
    padding: 2,
  },
  notCurrentSlide: {
    borderWidth: 2,
    borderColor: "rgba(0,0,0,0)",
    padding: 2,
  },
  presentationBox: {
    flexDirection: "row",
    alignItems: "center",
    paddingTop: 5,
    paddingRight: 20,
    paddingBottom: 5,
    paddingLeft: 10,
    borderBottomColor: "#363636",
    borderBottomWidth: 1,
    width: "100%",
  },
  finalPresentationBox: {
    flexDirection: "row",
    alignItems: "center",
    paddingTop: 5,
    paddingRight: 20,
    paddingBottom: 5,
    paddingLeft: 10,
    width: "100%",
  },
  // slidesSizeButtonsContainer: {
  //   marginLeft: "auto",
  // },
  // slidesSizeButtons: {
  //   all: "unset",
  //   margin: "0 10px",
  //   border: "1px solid #363636",
  //   padding: "0 7px",
  //   borderRadius: "4px",
  //   fontSize: "12px",
  // },
  refreshButton: {
    marginHorizontal: 10,
    borderWidth: 1,
    borderColor: "#363636",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
    fontSize: 12,
    color: "#f4f4f4",
  },
  whiteText: {
    color: "#f4f4f4",
  },
  biggerText: {
    fontSize: 20,
  },
});
